name: Build Docs
on:
  workflow_dispatch: {}
jobs:
  main:
    name: Build & Deploy Docs
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed

          # Modify as appropriate
          GH_PAGES_BRANCH: main

          # if your doc isn't in the root folder,
          # or Bikeshed otherwise can't find it:
          SOURCE: docs/index.bs